// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertsController from "./alerts_controller"
application.register("alerts", AlertsController)

import FormSubmitByTagController from "./form_submit_by_tag_controller"
application.register("form-submit-by-tag", FormSubmitByTagController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PageTransitionsController from "./page_transitions_controller"
application.register("page-transitions", PageTransitionsController)

import TrixController from "./trix_controller"
application.register("trix", TrixController)

import TurboController from "./turbo_controller"
application.register("turbo", TurboController)
